hello: 
	as -o hello.o hello.s
	ld -o out hello.o

greeting:
	as -o greeting.o greeting.s
	ld -o out greeting.o

upper:
	as -o upper.o upper.s
	ld -o out upper.o

max:
	as -o max_of_nums.o max_of_nums.s
	ld -o out max_of_nums.o

clean:
	rm *.o
	rm out
